.\"
.\" Copyright (c) 2022 Omar Polo
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd September 14, 2022
.Dt GALILEO 8
.Os
.Sh NAME
.Nm galileo
.Nd Gemini proxy for the World Wide Web
.Sh SYNOPSIS
.Nm
.Op Fl dnv
.Op Fl D Ar macro=value
.Op Fl f Ar file
.Sh DESCRIPTION
.Nm
is a Fast-CGI server that proxies the content of a Gemini capsule.
It has been designed to work out of the box with the
.Xr httpd 8
web server.
.Pp
.Nm
rereads its configuration file when it receives SIGHUP.
.Pp
The options are as follows:
.Bl -tag -width tenletters
.It Fl d
Do not daemonize and log to standard error.
.It Fl D Ar macro=value
Override the value of a macro used in the configuration file.
.It Fl f Ar file
Specify the configuration file.
The default is
.Pa /etc/galileo.conf .
.It Fl n
Parse the configuration file, report errors if any, and exit.
.It Fl v
Verbose mode.
.El
.Sh FILES
.Bl -tag -width /etc/galileo.conf -compact
.It Pa /etc/galileo.conf
Default location of the
.Xr galileo.conf 5
configuration file.
.El
.Sh SEE ALSO
.Xr galileo.conf 5 ,
.Xr httpd 8
.Sh AUTHORS
.An Omar Polo Aq Mt op@omarpolo.com
